baseURL = "http://andrii.bilor.us/"
languageCode = "en-us"
title = "Andrii Bilorus"
theme = "hugo-redlounge" 
publishDir = "docs"

[params]
	 sidebartitle = "Andrii Bilorus"
	 sidebartagline = "Trust me, I'm an engineer."
#	 sidebarphoto = "/img/photo.png"
     aboutpage = true

[[menu.main]]
    name = "About"
    url = "/about/"

[[menu.main]]
    name = "Notes"
    url = "/notes/"

[[menu.social]]
  	pre = "<i class='fa fa-twitter'></i>"
    url = "https://www.twitter.com/andriibilorus"
    identifier = "twitter"

[[menu.social]]
  	pre = "<i class='fa fa-github'></i>"
    url = "https://www.github.com/andrewscat"
    identifier = "github"

[[menu.social]]
  	pre = "<i class='fa fa-linkedin'></i>"
    url = "https://www.linkedin.com/in/andrii-bilorus-92491065/"
    identifier = "linkedin"

